//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЮсуповPractic1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Material { get; set; }
        public string Type { get; set; }
        public string Style { get; set; }
        public string Quantity_in_stock { get; set; }
    }
}
